### ISSUE TITLE
Unexpected compatibility issue with VsCode

### ISSUE THREAD

**Issue by lorenhicks** [fireplusteam/ios-swift-for-vs-code#3]
Getting the following error when attempting to install: "Can't install 'fireplusteam.vscode-ios' extension because it is not compatible with the current version of Visual Studio Code (version 1.85.1)." I have the most recent version of VSCode and this was published pretty recently. I feel like there should not be many compatibility issues already but I could be wrong.

**Comment by fireplusteam** [comment]
you need to install vs code at least 1.86

**Comment by fireplusteam** [comment]
1.85.1 is not supported
