### ISSUE TITLE
Enhancement: LLM support

### ISSUE THREAD

**Issue by mobile-appz** [fireplusteam/ios-swift-for-vs-code#4]
Feature request: LLM support

Presumably this has a swiftUI code interpreter? In future would it be possible to add LLM support, eg connected to something like continue.dev and use a local LLM to generate code that can be iterated over using the compiler until a valid solution is found? That would be really useful vs xcode.

**Comment by fireplusteam** [comment]
you can use copilot and similar stuff, also if continue.dev has an extension, it can be used in vs code, this extension did integrates of lsp and debugging compatibilities, others third party features can be used as well

**Comment by fireplusteam** [comment]
@mobile-appz , you have the same autocompletion support for SwiftUI as in xCode because it uses apple lsp server to provide the suggestions

**Comment by fireplusteam** [comment]
SwiftUI is supported

**Comment by mobile-appz** [comment]
> SwiftUI is supported

Thanks for the info. Does this run on Linux and if so can it compile the code and create iOS and MacOS apps on Linux? Or  does that process require Apple hardware and Apple software such as Xcode tools?

**Comment by fireplusteam** [comment]
You still need xCode to run lsp and ios frameworks
readme contains every extra steps you need to do in order to make it work

**Comment by fireplusteam** [comment]
MacOS is not supported at this stage, only iOS
