### ISSUE TITLE
can i config custom lldb init command ignore 'Stop reason: signal SIGUSR1' cause the app suspend?

### ISSUE THREAD

**Issue by touchmii** [fireplusteam/ios-swift-for-vs-code#6]
use this command can ignore SIGUSR1 fix this issue, xcode doesnott have this problem.

process handle --stop false SIGUSR1

![ScreenShot 2024-09-19 at 10 37 38 PM](https://github.com/user-attachments/assets/7667a24f-d547-4657-8544-6f5a64945a5b)

**Comment by touchmii** [comment]
place .lldbinit file in project root dir or home dir not work.

**Comment by fireplusteam** [comment]
Updated extension to 0.0.17 (probably you need to wait until it's available on a store)
update please on vs market and use the following:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "xcode-lldb",
            "name": "iOS: Run App & Debug",
            "request": "launch",
            "target": "app",
            "isDebuggable": true,
            "lldbCommands": [
                "process handle --stop false SIGUSR1"
            ]
        }
    ]
}
```

**Comment by fireplusteam** [comment]
update is live, let me know if it works for you
