### ISSUE TITLE
Autocompletion not working

### ISSUE THREAD

**Issue by NyxReloaded** [fireplusteam/ios-swift-for-vs-code#7]
### Description

Since the latest update of the extension, autocompletion has completely stopped working. 
The automatic suggestions that used to appear while typing code no longer show up. 
This is seriously affecting productivity and development.

### Steps to reproduce the bug:

1. Open Visual Studio Code.
2. Install/Update the extension to the latest version.
3. Open xcode project in vscode (using [Xcode iOS Swift IDE](https://marketplace.visualstudio.com/items?itemName=FirePlusTeam.vscode-ios) extension)
4. Open a file in a language supported by the extension (e.g., a .swift file).
5. Start typing code (e.g., a function, a variable, etc.).
6. Trigger suggest (ctrl + space)
7. Notice that no suggestions or autocompletion appear. (Only a "Loading..." text appear)

### Expected behavior
Autocompletion should provide relevant suggestions based on the typed code, as it did prior to the update.

### Actual behavior
No suggestions are provided during autocompletion.

### Additional informations

-  Extension version: v0.3.0
-  Visual Studio Code version: 1.91.1
-  Operating system:  macOS  15.0.1
-  Logs appear in console :

> [Error - 18:31:00] Request textDocument/inlayHint failed.
>   Message: sourcekitd request timed out
>   Code: -32001 
> [Error - 18:31:01] Request textDocument/semanticTokens/full failed.
>   Message: No language service for 'cpp-ghost-text-preview-widget-anysphere://jwchiymjab' found
>   Code: -3200

### Possible causes or suggestions:
I suspect the issue might be related to an issue with the new LSP client support. The previous version which use sourcekit-lsp works.

Thank you for your assistance in resolving this issue!

**Comment by fireplusteam** [comment]
Can you please provide more context or a simple example project where it's reproducible
Also, make sure that you need
1. Make sure that Xcode is installed in folder /Application/Xcode
2. Clean derived data and .vscode/.env and other related files
3. Open a folder containing the Xcode project
4. Select an Xcode project file and generate vs code workspace in vs code
5. Build successfully project

Also What is the version of Xcode?

**Comment by fireplusteam** [comment]
Also can you try to disable official swift extension and find out if it works ?

**Comment by fireplusteam** [comment]
That version also uses sourcekit-lsp, but we no longer rely on swift lang vscode extension, which allows us to support swift Testing natively. But looks like your sourcekitd service is down. Probably restarting that process or mac could also help. Also might be some issue with new macOS.
check if you have sourcekit-lsp by running command in terminal
`xcrun -f sourcekit-lsp`

**Comment by fireplusteam** [comment]
please try to update to 0.3.2 and let me know if it started to work

**Comment by fireplusteam** [comment]
feel free to reopen if it's still reproducible
